name: 'Branch Validator'
description: 'Verify that tag or commit is from specified branch'

inputs:
  target_branch:
    description: 'Branch to validate against'
    required: false
    default: 'main'
  tag_name:
    description: 'Tag name to validate (if empty, uses current HEAD)'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Validate branch
      shell: bash
      run: |
        TARGET_BRANCH="${{ inputs.target_branch }}"
        TAG_NAME="${{ inputs.tag_name }}"
        
        if [ -n "$TAG_NAME" ]; then
          COMMIT=$(git rev-list -n 1 "$TAG_NAME")
          echo "Checking tag '$TAG_NAME' (commit: $COMMIT)"
        else
          COMMIT=$(git rev-parse HEAD)
          echo "Checking current HEAD (commit: $COMMIT)"
        fi
        
        if git merge-base --is-ancestor "$COMMIT" "origin/$TARGET_BRANCH"; then
          echo "Commit is from branch '$TARGET_BRANCH'"
        else
          echo "Commit is NOT from branch '$TARGET_BRANCH'"
          exit 1
        fi