name: Is Commit
description: |
  Determines if the event is a regular push commit (not a PR merge/squash).
  Outputs `proceed=true` if it’s a normal commit, `proceed=false` otherwise.

inputs:
  github_token:
    description: "GitHub token to call the API"
    required: true

outputs:
  proceed:
    description: "‘true’ if this is a normal commit, ‘false’ if merge/squash commit"

runs:
  using: composite
  steps:
    - name: Initial actor & message check
      id: check
      shell: bash
      run: |
        ACTOR="${{ github.actor }}"
        MSG="${{ github.event.head_commit.message }}"
        echo "Commit actor: $ACTOR"
        echo "Commit message: $MSG"
        # if GitHub UI merge/squash (actor=web-flow) → skip
        if [[ "$ACTOR" == "web-flow" ]]; then
          echo "proceed=false" >> $GITHUB_OUTPUT
          exit 0
        fi
        # classic merge-commit
        if echo "$MSG" | grep -Eiq "merge pull request"; then
          echo "proceed=false" >> $GITHUB_OUTPUT
          exit 0
        fi
        # CLI squash (contains “(#123)” pattern)
        if echo "$MSG" | grep -Eiq "\(#[0-9]+\)"; then
          echo "proceed=false" >> $GITHUB_OUTPUT
          exit 0
        fi
        # otherwise maybe a plain commit
        echo "proceed=maybe" >> $GITHUB_OUTPUT

    - name: Check PR association via GitHub API
      if: steps.check.outputs.proceed == 'maybe'
      id: prcheck
      shell: bash
      run: |
        SHA="${{ github.event.head_commit.id }}"
        # Query the GH API for PRs touching this SHA
        prs=$(curl -s \
          -H "Accept: application/vnd.github.groot-preview+json" \
          -H "Authorization: Bearer ${{ inputs.github_token }}" \
          https://api.github.com/repos/${{ github.repository }}/commits/$SHA/pulls)
        count=$(echo "$prs" | jq 'length')
        if [ "$count" -gt 0 ]; then
          echo "proceed=false" >> $GITHUB_OUTPUT
        else
          echo "proceed=true"  >> $GITHUB_OUTPUT
        fi