name: Is Commit
description: |
  Determines whether a push is a plain commit (proceed=true) 
  or part of a PR merge/squash (proceed=false), *solely* by querying 
  the GitHub API for pull‐requests touching that SHA.

inputs:
  github_token:
    description: "GitHub token to call the API"
    required: true

outputs:
  proceed:
    description: "‘true’ if this is a normal commit, ‘false’ if it’s a PR merge/squash"

runs:
  using: composite
  steps:
    - name: Check pull request association via GitHub API
      id: prcheck
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        SHA:         ${{ github.event.head_commit.id }}
        REPO:        ${{ github.repository }}
      run: |
        echo "Checking commit $SHA in repo $REPO…"
        prs=$(curl -s \
          -H "Accept: application/vnd.github.groot-preview+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          "https://api.github.com/repos/$REPO/commits/$SHA/pulls")
        count=$(echo "$prs" | jq 'length')
        if [ "$count" -gt 0 ]; then
          echo "Found $count PR(s) — this is a merge/squash → skip"
          echo "proceed=false" >> $GITHUB_OUTPUT
        else
          echo "No PR associated → normal commit"
          echo "proceed=true"  >> $GITHUB_OUTPUT
        fi