---
name: Create/Replace tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create or replace'
        required: true
        type: string
      force:
        description: 'Overwrite existing tag'
        required: false
        type: boolean
        default: true

concurrency:
  group: manual-tag-${{ inputs.tag }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Force create/replace tag
        uses: Mad-Pixels/github-workflows/actions/github-create-tag@v1
        with:
          tag: ${{ inputs.tag }}
          force: ${{ inputs.force }}
          token: ${{ secrets.PAT_TOKEN }}
