name: Checks

on:
  workflow_call:
    secrets:
      gitleaks: 
        required: true

jobs:
  eslint:
    name: ESLint
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - name: Invoke
        uses: Mad-Pixels/github-workflows/.github/actions/taskfile-runner@main
        with:
          command: node/lint

  prettier:
    name: Prettier
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - name: Invoke
        uses: Mad-Pixels/github-workflows/.github/actions/taskfile-runner@main
        with:
          command: node/format

  audit: 
    name: Audit 
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - name: Invoke
        uses: Mad-Pixels/github-workflows/.github/actions/taskfile-runner@main
        with:
          command: node/audit
  
  type-check:
    name: TypeCheck
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - name: Invoke
        uses: Mad-Pixels/github-workflows/.github/actions/taskfile-runner@main
        with:
          command: node/type-check
        
