name: Sync Directory to S3
description: Uploads a local directory to an S3 bucket with optional prefix and cleanup.

inputs:
  aws_access_key:
    description: AWS access key ID
    required: true
  aws_secret_key:
    description: AWS secret access key
    required: true
  aws_region:
    description: AWS region (e.g. us-east-1)
    required: true
  bucket_name:
    description: Name of the S3 bucket
    required: true
  source_dir:
    description: Local directory to sync
    required: true
  bucket_prefix:
    description: Optional path prefix in the S3 bucket
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id:     ${{ inputs.aws_access_key }}
        aws-secret-access-key: ${{ inputs.aws_secret_key }}
        aws-region:            ${{ inputs.aws_region }}

    - name: Test AWS connection step by step
      shell: bash
      run: |
        echo "=== Testing AWS CLI ==="
        aws --version
  
        echo "=== Testing credentials ==="
        aws sts get-caller-identity
    
        echo "=== Testing S3 access ==="
        aws s3 ls
    
        echo "=== Testing specific bucket ==="
        aws s3 ls s3://${{ inputs.bucket_name }}/
    
        echo "=== Testing bucket location ==="
        aws s3api get-bucket-location --bucket ${{ inputs.bucket_name }}
    
        echo "=== Testing bucket policy ==="
        aws s3api get-bucket-policy --bucket ${{ inputs.bucket_name }} || echo "No bucket policy found"

    - name: Sync directory to S3
      shell: bash
      run: |
        DEST="s3://${{ inputs.bucket_name }}/${{ inputs.bucket_prefix }}"
        echo "Syncing ${{ inputs.source_dir }} → $DEST"
        aws s3 sync "${{ inputs.source_dir }}" "$DEST" \
          --delete \
          --exclude ".git/*" \
          --exclude ".github/*" \
          --exclude ".gitignore" \
          --exclude ".gitattributes"