name: 'Terraform Format Check'
description: 'Checks Terraform formatting with `terraform fmt -check -diff -recursive`.'

inputs:
  tf_dir:
    description: 'Path to the Terraform directory'
    required: false
    default: './'

  tf_version:
    description: 'Terraform version to use'
    required: false
    default: '1.6.1'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.tf_version }}

    - name: Terraform fmt check
      shell: bash
      working-directory: ${{ inputs.tf_dir }}
      run: terraform fmt -check -diff -recursive