---
name: Build from Artifact

on:
  workflow_dispatch:

jobs:
  build-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build app bundle
        run: |
          mkdir -p dist && echo "hello" > dist/index.html
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: dist/

  docker:
    runs-on: ubuntu-latest
    needs: build-artifact
    steps:
      - name: Build & Push using artifact as context
        uses: Mad-Pixels/github-workflows/actions/docker-build-push@v1
        with:
          docker_user: ${{ secrets.DOCKERHUB_USERNAME }}
          docker_token: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: myuser/static-site
          tag: ${{ github.run_number }}
          artifact_name: web-dist
          context_path: .   
          dockerfile_path: Dockerfile 
          platforms: linux/amd64,linux/arm64

