name: GolangCI Lint
description: Run golangci-lint with custom Go version and directory

inputs:
  go_dir:
    description: "Directory with Go code"
    required: false
    default: "./"
  go_version:
    description: "Go version to use"
    required: false
    default: "1.24"
  golangci_lint_version:
    description: "Version of golangci-lint"
    required: false
    default: "v2.1.2"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ inputs.go_version }}

    - name: Install golangci-lint
      shell: bash
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
          | sh -s -- -b /usr/local/bin ${{ inputs.golangci_lint_version }}

    - name: Run golangci-lint
      shell: bash
      working-directory: ${{ inputs.go_dir }}
      run: golangci-lint run --timeout=5m