name: ECR Push

description: Push Docker image to AWS ECR

inputs:
  aws_access_key_id:
    description: 'AWS access key ID'
    required: true
  aws_secret_access_key:
    description: 'AWS secret access key'
    required: true
  aws_region:
    description: 'AWS region'
    required: true
  aws_account_id:
    description: 'AWS account ID'
    required: true

  image:
    description: 'Local image name with tag (e.g. my-repo:tag)'
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ inputs.aws_access_key_id }}
        aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
        aws-region: ${{ inputs.aws_region }}

    - name: Login to Amazon ECR
      shell: bash
      run: |
        aws ecr get-login-password --region "${{ inputs.aws_region }}" \
          | docker login --username AWS --password-stdin "${{ inputs.aws_account_id }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com"

    - name: Tag and push image to ECR
      shell: bash
      run: |
        LOCAL_IMAGE="${{ inputs.image }}"
        IMAGE_NAME=$(echo "$LOCAL_IMAGE" | cut -d':' -f1)
        IMAGE_TAG=$(echo "$LOCAL_IMAGE" | cut -d':' -f2)
        ECR_REGISTRY="${{ inputs.aws_account_id }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com"

        docker tag "$LOCAL_IMAGE" "$ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG"
        docker push "$ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG"