name: Task Runner

description: Run Taskfile command using task binary from container, with Docker socket passthrough

inputs:
  go_dir:
    description: "Working directory inside the project"
    required: false
    default: "."
  command:
    description: "Task command to run"
    required: true
  vars:
    description: "Optional environment variables in format key:value,key:value"
    required: false
  image:
    description: "Task image (used only to extract binary)"
    required: false
    default: "ghcr.io/mad-pixels/images/taskfile:v3.44.1"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Extract task binary from container
      shell: bash
      run: |
        docker run --rm --entrypoint cat \
          ${{ inputs.image }} /usr/local/bin/task > "$GITHUB_WORKSPACE/task"
        chmod +x "$GITHUB_WORKSPACE/task"

    - name: Parse and export environment variables
      if: ${{ inputs.vars != '' }}
      shell: bash
      run: |
        echo "${{ inputs.vars }}" | tr ',' '\n' | while IFS=: read -r key value; do
          echo "$key=$value" >> "$GITHUB_ENV"
        done

    - name: Run Task on host
      shell: bash
      working-directory: ${{ inputs.go_dir }}
      run: |
        "$GITHUB_WORKSPACE/task" ${{ inputs.command }}
