---
name: Task Runner
description: Invoke Taskfile commands

inputs:
  command:
    description: 'Task command to run for invoke'
    required: true
  vars:
    description: 'Envs for command, format: (key=value,key=value)'
    required: false
  dir:
    description: 'Working directory'
    required: false
    default: '.'
  version:
    description: 'Taskfile version'
    required: false
    default: '3.44.1'

outputs:
  task_version:
    description: 'Installed Task version'
    value: ${{ steps.install.outputs.version }}
  task_output:
    description: 'Task command output'
    value: ${{ steps.run.outputs.output }}

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Validate Taskfile exists
      shell: bash
      working-directory: ${{ inputs.dir }}
      run: |
        set -euo pipefail
        
        if [[ ! -f "Taskfile.yml" && ! -f "Taskfile.yaml" ]]; then
          echo "❌ No Taskfile found in ${{ inputs.dir }}"
          echo "Expected: Taskfile.yml or Taskfile.yaml"
          exit 1
        fi
        
        echo "✅ Taskfile found"

    - name: Detect architecture
      id: arch
      shell: bash
      run: |
        set -euo pipefail
        
        ARCH=$(uname -m)
        case "$ARCH" in
          x86_64) ARCH="amd64" ;;
          aarch64|arm64) ARCH="arm64" ;;
          *) echo "❌ Unsupported architecture: $ARCH" && exit 1 ;;
        esac

        echo "arch=$ARCH" >> $GITHUB_OUTPUT

    - name: Cache Task binary
      id: cache
      uses: actions/cache@v4
      with:
        path: ${{ env.HOME }}/.cache/task/task-${{ inputs.version }}-${{ steps.arch.outputs.arch }}
        key: task-${{ inputs.version }}-${{ steps.arch.outputs.arch }}

    - name: Download Task binary
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        set -euo pipefail
        
        VERSION="${{ inputs.version }}"
        ARCH="${{ steps.arch.outputs.arch }}"
        echo "⬇️  Downloading Task v$VERSION for $ARCH..."

        mkdir -p ~/.cache/task
        curl -sSLo /tmp/task.tgz --fail "https://github.com/go-task/task/releases/download/v${VERSION}/task_linux_${ARCH}.tar.gz"
        tar -xzf /tmp/task.tgz -C /tmp
        
        TASK_BINARY=$(find /tmp -maxdepth 2 -type f -name "task" -perm -111 | head -n 1)
        if [[ -z "$TASK_BINARY" ]]; then
          echo "❌ Task binary not found in archive"
          exit 1
        fi

        mv "$TASK_BINARY" ~/.cache/task/task-$VERSION-$ARCH

    - name: Install Task binary
      id: install
      shell: bash
      run: |
        set -euo pipefail
        
        VERSION="${{ inputs.version }}"
        ARCH="${{ steps.arch.outputs.arch }}"

        if ! mkdir -p ~/.local/bin; then
          echo "❌ Failed to create ~/.local/bin"
          exit 1
        fi

        if ! cp ~/.cache/task/task-$VERSION-$ARCH ~/.local/bin/task; then
          echo "❌ Failed to copy task binary"
          exit 1
        fi

        if ! chmod +x ~/.local/bin/task; then
          echo "❌ Failed to make task executable"
          exit 1
        fi

        echo "$HOME/.local/bin" >> "$GITHUB_PATH"
        if ! ~/.local/bin/task --version >/dev/null 2>&1; then
          echo "❌ Task binary verification failed"
          exit 1
        fi

        INSTALLED_VERSION=$(~/.local/bin/task --version | grep -o 'v[0-9.]*')
        echo "✅ Installed task $INSTALLED_VERSION"
        echo "version=$INSTALLED_VERSION" >> $GITHUB_OUTPUT

    - name: Export environment variables
      if: ${{ inputs.vars != '' }}
      shell: bash
      run: |
        set -euo pipefail
    
        echo "🌐 Exporting env vars:"
        IFS=',' read -ra VARS <<< "${{ inputs.vars }}"
        for var in "${VARS[@]}"; do
          pair="$(echo "$var" | xargs)"
          [[ -z "$pair" ]] && continue

          key="${pair%%=*}"
          value="${pair#*=}"
          if [[ "$value" == "$key" ]]; then
            echo "❌ Invalid var format: $pair (missing '=' separator)"
            exit 1
          fi
          if [[ -z "$key" ]]; then
            echo "❌ Invalid var (empty key): $pair"
            exit 1
          fi

          delim="ENV_${key}_$RANDOM$RANDOM"
          {
            echo "$key<<$delim"
            printf "%s\n" "$value"
            echo "$delim"
          } >> "$GITHUB_ENV"
        done

    - name: Run Taskfile command
      id: run
      shell: bash
      working-directory: ${{ inputs.dir }}
      run: |
        set -euo pipefail
        
        echo "🚀 Running task ${{ inputs.command }}"

        set +e
        OUTPUT=$(task ${{ inputs.command }} 2>&1)
        EXIT_CODE=$?
        set -e

        printf "%s\n" "$OUTPUT"
        
        DELIM="__TASK_OUTPUT_$(date +%s%N)__"
        {
          echo "output<<$DELIM"
          printf "%s\n" "$OUTPUT"
          echo "$DELIM"
        } >> "$GITHUB_OUTPUT"
        if [[ $EXIT_CODE -ne 0 ]]; then
          echo "❌ Task failed with exit code $EXIT_CODE"
          exit $EXIT_CODE
        fi
        
        echo "✅ Task completed successfully"

    - name: Task Runner Summary
      shell: bash
      run: |
        set -euo pipefail
        
        {
          echo "## 🧰 Task Runner Summary"
          echo "- Command: \`${{ inputs.command }}\`"
          echo "- Directory: \`${{ inputs.dir }}\`"
          echo "- Task version: \`${{ steps.install.outputs.version }}\`"
        } >> "$GITHUB_STEP_SUMMARY"

