name: Task Runner

description: Run Taskfile

inputs:
  go_dir:
    description: "Working directory inside the project"
    required: false
    default: "."
  command:
    description: "Task command to run"
    required: true
  vars:
    description: "Optional environment variables in format key:value,key:value"
    required: false
  version:
    description: "Task version to use"
    required: false
    default: "3.44.1"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Detect architecture and download task binary
      shell: bash
      run: |
        set -euo pipefail

        ARCH=$(uname -m)
        case "$ARCH" in
          x86_64) ARCH="amd64" ;;
          aarch64) ARCH="arm64" ;;
          *) echo "Unsupported architecture: $ARCH" && exit 1 ;;
        esac

        VERSION="${{ inputs.version }}"
        echo "Downloading Task v$VERSION for $ARCH..."

        curl -sL "https://github.com/go-task/task/releases/download/v${VERSION}/task_linux_${ARCH}.tar.gz" \
          | tar -xz -C /tmp

        sudo mv /tmp/task /usr/local/bin/task
        sudo chmod +x /usr/local/bin/task
        task --version

    - name: Export environment variables
      if: ${{ inputs.vars != '' }}
      shell: bash
      run: |
        echo "${{ inputs.vars }}" | tr ',' '\n' | while IFS=: read -r key value; do
          echo "$key=$value" >> $GITHUB_ENV
        done

    - name: Run Task
      shell: bash
      working-directory: ${{ inputs.go_dir }}
      run: |
        task ${{ inputs.command }}
