name: Check 

on:
  push:
    branches:
      - '**'        
      - '!main'     
    paths:
      - '**.rs'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  pull_request:
    branches:
      - main
    paths:
      - '**.rs'
      - '**/Cargo.toml'
      - '**/Cargo.lock'

jobs:
  check:
    uses: Mad-Pixels/github-workflows/.github/workflows/rust-check.yml@main
    with:
      working-directory: "./actions"
