name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    uses: github.com/Mad-Pixels/github-workflows/.github/workflows/rust-check.yml@main
    with:
      working-directory: "./"
  