name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  rust-ci:
    uses: Mad-Pixels/github-workflows/.github/workflows/rust-ci.yml@dev
    with:
      working-directory: "actions"
      binaries: '["first-binary", "second-binary"]'
      version: ${{ github.event.head_commit.message }}