name: Checks

on:
  workflow_call:
    secrets:
      gitleaks: 
        required: true

jobs:
  yamllint:
    name: Linter 
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - name: Invoke
        uses: Mad-Pixels/github-workflows/actions/taskfile-runner@main
        with:
          command: yamllint
  
  leaks:
    name: GitLeaks
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.gitleaks }}
