name: Check PR

on:
  workflow_call:
    outputs:
      should-run:
        description: "Whether the workflow should run"
        value: ${{ jobs.check-pr.outputs.should-run }}

jobs:
  check-pr:
    runs-on: ubuntu-latest
    outputs:
      should-run: ${{ steps.check.outputs.should-run }}
    steps:
      - id: check
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "should-run=true" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "push" && ! "${{ github.ref }}" =~ ^refs/heads/.*$ ]]; then
            echo "should-run=true" >> $GITHUB_OUTPUT
          else
            PR_NUMBER=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/pulls" | jq '. | length')
            if [[ "$PR_NUMBER" == "0" ]]; then
              echo "should-run=true" >> $GITHUB_OUTPUT
            else
              echo "should-run=false" >> $GITHUB_OUTPUT
            fi
          fi