name: Delete All Merged Branches Except Main

on:
  workflow_call:

jobs:
  delete-merged-branches:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Нужно видеть всю историю веток

      - name: Delete merged branches except main
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"

          echo "Fetching all remote branches..."
          git fetch --all --prune

          echo "Finding merged branches (excluding main)..."

          # Ищем все ветки, смёрженные в main, но не сам main
          MERGED_BRANCHES=$(git branch -r --merged origin/main | grep -v 'origin/main$' | sed 's|origin/||')

          if [[ -z "$MERGED_BRANCHES" ]]; then
            echo "No merged branches to delete."
            exit 0
          fi

          echo "Merged branches to delete:"
          echo "$MERGED_BRANCHES"

          COUNT=0

          for branch in $MERGED_BRANCHES; do
            echo "Deleting branch: $branch"
            git push origin --delete "$branch"
            COUNT=$((COUNT+1))
          done

          echo "Deleted $COUNT branches."
