name: Delete All Merged Branches

on:
  workflow_call:

jobs:
  delete-merged-branches:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Delete merged branches
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"

          echo "Fetching all remote branches..."
          git fetch --all --prune

          echo "Looking for merged branches..."
          MERGED_BRANCHES=$(git branch -r --merged origin/main | grep -v 'origin/main' | grep -v 'origin/release/' | sed 's|origin/||')

          if [[ -z "$MERGED_BRANCHES" ]]; then
            echo "No merged branches found."
            exit 0
          fi

          echo "Merged branches to delete:"
          echo "$MERGED_BRANCHES"

          for branch in $MERGED_BRANCHES; do
            echo "Deleting branch: $branch"
            git push origin --delete "$branch"
          done
