name: Task Runner

on:
  workflow_call:
    inputs:
      go_dir:
        type: string
        required: false
        default: "./"
      go_version:
        type: string
        required: false
        default: "1.24"
      command:
        type: string
        required: true
      vars:
        type: string
        required: false

jobs:
  task:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.go_dir }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go_version }}

      - name: Install Task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

      - name: Create buildx builder (required for ARM64)
        run: |
          docker buildx create --name applingo-builder --driver docker-container --use || true
          docker buildx inspect --bootstrap

      - name: Export VARS as env
        if: ${{ inputs.vars != '' }}
        run: |
          echo "${{ inputs.vars }}" | tr ',' '\n' | while IFS=: read -r key value; do
            echo "$key=$value" >> $GITHUB_ENV
          done

      - name: Run Task
        run: task ${{ inputs.command }}