name: Node Build

on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        default: ""
        type: string
        description: "Directory containing Vue project (package.json)"
      node-version:
        required: false
        default: "20"
        type: string
        description: "Node.js version to use"
      artifacts-name:
        required: false
        default: artifacts
        type: string
        description: "Name of the output artifacts"

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
          cache-dependency-path: ${{ inputs.working-directory }}/package-lock.json

      - name: Install dependencies
        working-directory: ${{ inputs.working-directory }}
        run: npm ci

      - name: Build
        working-directory: ${{ inputs.working-directory }}
        run: npm run build

      - name: Prepare artifacts
        run: |
          mkdir -p artifacts
          DIST_DIR="${{ inputs.working-directory }}/dist"
          if [ ! -d "$DIST_DIR" ]; then
            echo "Error: Build directory not found: $DIST_DIR"
            exit 1
          fi
          cp -r "$DIST_DIR" artifacts/

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifacts-name }}
          path: artifacts/dist/
          if-no-files-found: error