name: Terraform Format Check

on:
  workflow_call:
    inputs:
      tf_dir:
        type: string
        required: false
        default: "./"
      tf_version:
        type: string
        required: false
        default: '1.6.1'

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.tf_dir }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.tf_version }}

      - name: Terraform fmt check
        run: terraform fmt -check -diff -recursive
